// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SingleAppView.www.w3schools.com {
    
}


[System.ServiceModel.ServiceContractAttribute(Namespace="SingleAppView.www.w3schools.com", ConfigurationName="TempConvertSoap")]
public interface TempConvertSoap {
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.w3schools.com/webservices/FahrenheitToCelsius")]
    string FahrenheitToCelsius(string Fahrenheit);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.w3schools.com/webservices/FahrenheitToCelsius", AsyncPattern=true)]
    System.IAsyncResult BeginFahrenheitToCelsius(string Fahrenheit, System.AsyncCallback asyncCallback, object userState);
    
    string EndFahrenheitToCelsius(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.w3schools.com/webservices/CelsiusToFahrenheit")]
    string CelsiusToFahrenheit(string Celsius);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.w3schools.com/webservices/CelsiusToFahrenheit", AsyncPattern=true)]
    System.IAsyncResult BeginCelsiusToFahrenheit(string Celsius, System.AsyncCallback asyncCallback, object userState);
    
    string EndCelsiusToFahrenheit(System.IAsyncResult result);
}

public interface TempConvertSoapChannel {
}

public class TempConvertSoapClient : System.ServiceModel.ClientBase<TempConvertSoap>, TempConvertSoap {
    
    public TempConvertSoapClient() {
    }
    
    public TempConvertSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public TempConvertSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public TempConvertSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public TempConvertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public string FahrenheitToCelsius(string Fahrenheit) {
        return base.Channel.FahrenheitToCelsius(Fahrenheit);
    }
    
    public System.IAsyncResult BeginFahrenheitToCelsius(string Fahrenheit, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginFahrenheitToCelsius(Fahrenheit, asyncCallback, userState);
    }
    
    public string EndFahrenheitToCelsius(System.IAsyncResult result) {
        return base.Channel.EndFahrenheitToCelsius(result);
    }
    
    public string CelsiusToFahrenheit(string Celsius) {
        return base.Channel.CelsiusToFahrenheit(Celsius);
    }
    
    public System.IAsyncResult BeginCelsiusToFahrenheit(string Celsius, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginCelsiusToFahrenheit(Celsius, asyncCallback, userState);
    }
    
    public string EndCelsiusToFahrenheit(System.IAsyncResult result) {
        return base.Channel.EndCelsiusToFahrenheit(result);
    }
    
    protected override TempConvertSoap CreateChannel() {
        return ((TempConvertSoap)(new TempConvertSoapChannel(this)));
    }
    
    private class TempConvertSoapChannel : ChannelBase<TempConvertSoap>, TempConvertSoap {
        
        public TempConvertSoapChannel(System.ServiceModel.ClientBase<TempConvertSoap> client) : 
                base(client) {
        }
        
        public string FahrenheitToCelsius(string Fahrenheit) {
            object[] args = new object[] {
                    Fahrenheit};
            return ((string)(base.Invoke("FahrenheitToCelsius", args)));
        }
        
        public System.IAsyncResult BeginFahrenheitToCelsius(string Fahrenheit, System.AsyncCallback asyncCallback, object userState) {
            return base.BeginInvoke("FahrenheitToCelsius", new object[] {
                        Fahrenheit}, asyncCallback, userState);
        }
        
        public string EndFahrenheitToCelsius(System.IAsyncResult result) {
            object[] args = new object[0];
            return ((string)(base.EndInvoke("FahrenheitToCelsius", args, result)));
        }
        
        public string CelsiusToFahrenheit(string Celsius) {
            object[] args = new object[] {
                    Celsius};
            return ((string)(base.Invoke("CelsiusToFahrenheit", args)));
        }
        
        public System.IAsyncResult BeginCelsiusToFahrenheit(string Celsius, System.AsyncCallback asyncCallback, object userState) {
            return base.BeginInvoke("CelsiusToFahrenheit", new object[] {
                        Celsius}, asyncCallback, userState);
        }
        
        public string EndCelsiusToFahrenheit(System.IAsyncResult result) {
            object[] args = new object[0];
            return ((string)(base.EndInvoke("CelsiusToFahrenheit", args, result)));
        }
    }
}
